# Generated by Django 3.0.3 on 2020-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pankaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(verbose_name='Roll')),
            ],
        ),
    ]
