# Generated by Django 3.0.3 on 2020-02-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0002_pankaj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pankaj',
        ),
    ]
