# Generated by Django 3.0.3 on 2020-02-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectv1', '0003_delete_pankaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(default=' ', max_length=100, verbose_name='Inspector Name')),
                ('category_name', models.CharField(default=' ', max_length=100, verbose_name='Category Name')),
                ('site_name', models.CharField(default=' ', max_length=100, verbose_name='Site nName')),
                ('site_id', models.IntegerField(default='0', verbose_name='Site Id')),
                ('inspect_id', models.IntegerField(default='0', verbose_name='Inspector Id')),
                ('cat_id', models.IntegerField(default='0', verbose_name='Category Id')),
                ('item_id', models.IntegerField(default='0', verbose_name='Item Id')),
                ('fieldname', models.CharField(default=' ', max_length=100, verbose_name='value')),
                ('items', models.CharField(default=' ', max_length=100, verbose_name='items')),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'Inspect_Item',
                'verbose_name_plural': 'Inspected Items',
            },
        ),
        migrations.RenameModel(
            old_name='sub',
            new_name='Subsdiery',
        ),
        migrations.DeleteModel(
            name='Inspect_Item',
        ),
        migrations.RenameField(
            model_name='itemincategory',
            old_name='Show_In_Section',
            new_name='show_in_section',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='Subsdairy',
            new_name='subsdairy',
        ),
        migrations.RenameField(
            model_name='stoffice',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='Stoffice',
        ),
        migrations.AddField(
            model_name='sites',
            name='stoffice',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inspectv1.StOffice'),
        ),
    ]
